ADAPTER_ID = "orbitfabric-openobsw-opensvf"
ADAPTER_VERSION = "0.1.0.dev0"
INTEGRATION_ID = "orbitfabric-openobsw-opensvf"
INTEGRATION_SCHEMA_VERSION = "0.1-candidate"
PROFILE_VERSION = "0.1-candidate"
RESULT_VERSION = "0.2-candidate"

PROJECT_OPERATION = "project"
VERIFICATION_OPERATION = "verification_projection"
SCENARIO_ROLE = "scenario"
